const { GoogleGenAI } = require("@google/genai");

// Check if API key is provided
const apiKey = process.env.GOOGLE_API_KEY || process.env.GEMINI_API_KEY;
let ai = null;

if (apiKey) {
  try {
    ai = new GoogleGenAI({ apiKey });
    console.log("🤖 Gemini AI Service initialized successfully.");
  } catch (err) {
    console.error("❌ Failed to initialize Gemini AI SDK: ", err.message);
  }
} else {
  console.log("⚠️ No GOOGLE_API_KEY or GEMINI_API_KEY found. AI Service will run in Mock/Offline mode.");
}

// Highly comprehensive static diagnostic data for Offline/Mock mode
const offlineMedicalKnowledge = [
  {
    keywords: ["chest pain", "breath", "shortness of breath", "tightness", "left arm", "sweat"],
    response: {
      symptoms: ["Chest pain", "Shortness of breath"],
      conditions: [
        {
          name: "Angina / Suspected Myocardial Infarction (Heart Attack)",
          confidence: 90,
          explanation: "Chest pain or pressure, especially spreading to the arm or accompanied by breathing difficulties, can indicate a lack of blood flow to the heart.",
          otcMedicines: [
            {
              name: "Aspirin",
              dosage: "325mg (chewed immediately if advised by emergency services)",
              duration: "Single dose"
            }
          ]
        }
      ],
      emergencyRedFlag: true,
      emergencyAdvice: "🚨 CRITICAL WARNING: These symptoms suggest a potential cardiac emergency. Please call 911 or visit the nearest emergency room immediately. Do not drive yourself.",
      generalDisclaimer: "Disclaimer: This assessment is generated by an AI assistant for informational purposes only. It does not replace professional clinical evaluation."
    }
  },
  {
    keywords: ["fever", "cough", "sore throat", "runny nose", "cold", "congestion"],
    response: {
      symptoms: ["Fever", "Cough", "Runny nose"],
      conditions: [
        {
          name: "Common Cold / Viral Upper Respiratory Infection",
          confidence: 85,
          explanation: "Mild fever combined with a dry or productive cough and nasal congestion is highly indicative of a viral cold.",
          otcMedicines: [
            {
              name: "Paracetamol (Acetaminophen)",
              dosage: "500mg-650mg every 4-6 hours (Max 4g/day)",
              duration: "3-5 days"
            },
            {
              name: "Dextromethorphan (Cough Suppressant)",
              dosage: "10-20mg every 4 hours or 30mg every 6-8 hours",
              duration: "3-5 days"
            }
          ]
        },
        {
          name: "Influenza (Flu)",
          confidence: 60,
          explanation: "Sudden onset of high fever, muscle aches, sore throat, and severe fatigue suggests the influenza virus.",
          otcMedicines: [
            {
              name: "Ibuprofen",
              dosage: "200mg-400mg every 6 hours with food (Max 1200mg/day)",
              duration: "3-5 days"
            }
          ]
        }
      ],
      emergencyRedFlag: false,
      emergencyAdvice: "Advise resting, drinking plenty of fluids. Seek medical attention if fever exceeds 103°F (39.4°C) or lasts more than 3 days.",
      generalDisclaimer: "Disclaimer: This assessment is generated by an AI assistant for informational purposes only. It does not replace professional clinical evaluation."
    }
  },
  {
    keywords: ["headache", "migraine", "temple", "throbbing", "stress"],
    response: {
      symptoms: ["Headache", "Throbbing pain"],
      conditions: [
        {
          name: "Tension Headache",
          confidence: 80,
          explanation: "A dull, aching pain or band-like tightness around the forehead, commonly triggered by stress or muscle strain.",
          otcMedicines: [
            {
              name: "Ibuprofen",
              dosage: "400mg with food",
              duration: "As needed, maximum 3 days consecutively"
            },
            {
              name: "Paracetamol",
              dosage: "500mg",
              duration: "As needed"
            }
          ]
        },
        {
          name: "Migraine",
          confidence: 50,
          explanation: "Unilateral, throbbing headache, often accompanied by sensitivity to light/sound or nausea.",
          otcMedicines: [
            {
              name: "Acetaminophen/Aspirin/Caffeine Combination (e.g. Excedrin)",
              dosage: "2 tablets at onset of symptoms",
              duration: "Single dose"
            }
          ]
        }
      ],
      emergencyRedFlag: false,
      emergencyAdvice: "Seek emergency care if this is the 'worst headache of your life', or is accompanied by fever, stiff neck, confusion, or difficulty speaking.",
      generalDisclaimer: "Disclaimer: This assessment is generated by an AI assistant for informational purposes only. It does not replace professional clinical evaluation."
    }
  },
  {
    keywords: ["stomach", "ache", "acid", "heartburn", "diarrhea", "cramp", "indigestion", "nausea"],
    response: {
      symptoms: ["Stomach ache", "Acid reflux", "Nausea"],
      conditions: [
        {
          name: "Gastroesophageal Reflux Disease (GERD) / Heartburn",
          confidence: 75,
          explanation: "Burning sensation in the chest or upper abdomen after eating, caused by stomach acid flowing back into the esophagus.",
          otcMedicines: [
            {
              name: "Omeprazole (Antacid)",
              dosage: "20mg once daily in the morning, 30 mins before breakfast",
              duration: "14 days max for OTC use"
            },
            {
              name: "Antacid Tablets (Calcium Carbonate)",
              dosage: "2-4 tablets chewed as symptoms occur",
              duration: "As needed"
            }
          ]
        },
        {
          name: "Gastroenteritis (Stomach Flu)",
          confidence: 60,
          explanation: "Inflammation of stomach and intestines, usually viral, causing cramping, diarrhea, and nausea.",
          otcMedicines: [
            {
              name: "Oral Rehydration Salts (ORS)",
              dosage: "1 sachet dissolved in 1L water, sip continuously",
              duration: "2-3 days"
            },
            {
              name: "Loperamide (if experiencing severe watery diarrhea without fever)",
              dosage: "4mg initially, then 2mg after each loose stool (Max 8mg/day)",
              duration: "1-2 days"
            }
          ]
        }
      ],
      emergencyRedFlag: false,
      emergencyAdvice: "Seek emergency attention if you have severe, localized abdominal pain (possible appendicitis), bloody stools, persistent vomiting, or signs of severe dehydration.",
      generalDisclaimer: "Disclaimer: This assessment is generated by an AI assistant for informational purposes only. It does not replace professional clinical evaluation."
    }
  }
];

const analyzeSymptoms = async (symptomText) => {
  const query = symptomText.toLowerCase();

  // If Gemini API is available and initialized, call it!
  if (ai) {
    try {
      const prompt = `
        You are a highly experienced and compassionate medical assistant AI.
        Analyze the following user-described symptoms: "${symptomText}".
        
        Respond with a JSON object. Ensure the format matches this schema exactly, and do NOT include markdown wraps other than the JSON itself.
        
        Schema:
        {
          "symptoms": ["list of key symptoms identified"],
          "conditions": [
            {
              "name": "Condition/Disease Name",
              "confidence": 75, // integer percentage confidence (0-100)
              "explanation": "Brief explanation of why symptoms suggest this condition",
              "otcMedicines": [
                {
                  "name": "Recommended OTC Medicine",
                  "dosage": "Suggested dosage details",
                  "duration": "Suggested duration (e.g. 3-5 days)"
                }
              ]
            }
          ],
          "emergencyRedFlag": false, // boolean, set to true if symptoms indicate emergency (e.g. severe chest pain, breathing difficulty, stroke signs, sudden loss of consciousness)
          "emergencyAdvice": "Advice warning to visit emergency room or doctor immediately",
          "generalDisclaimer": "A safety warning stating that this is an AI recommendation and not a substitute for clinical advice."
        }
      `;

      // In @google/genai SDK, generateContent is called via: ai.models.generateContent
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json"
        }
      });

      const responseText = response.text || response.candidates[0].content.parts[0].text;
      return JSON.parse(responseText);
    } catch (err) {
      console.error("🤖 Gemini API failed, switching to offline fallback diagnostic service: ", err.message);
    }
  }

  // Offline / Mock fallback analyzer
  console.log("🔌 Running diagnostic analysis in offline mock database...");
  
  // Find a match based on keywords
  for (const knowledge of offlineMedicalKnowledge) {
    const isMatch = knowledge.keywords.some((keyword) => query.includes(keyword));
    if (isMatch) {
      return { ...knowledge.response, symptoms: [symptomText] };
    }
  }

  // Default general response if no keywords match
  return {
    symptoms: [symptomText],
    conditions: [
      {
        name: "General Malady / Mild Seasonal Infection",
        confidence: 65,
        explanation: "Based on your description, you may be experiencing a mild seasonal or environmental reaction. Rest and hydration are advised.",
        otcMedicines: [
          {
            name: "Paracetamol",
            dosage: "500mg every 6 hours as needed for discomfort or fever",
            duration: "2-3 days"
          },
          {
            name: "Multivitamins / Vitamin C",
            dosage: "1 tablet daily after food",
            duration: "7 days"
          }
        ]
      }
    ],
    emergencyRedFlag: false,
    emergencyAdvice: "Monitor your symptoms closely. If they worsen, or if you develop breathing difficulties, high fever, or severe localized pain, consult a healthcare provider immediately.",
    generalDisclaimer: "Disclaimer: This assessment is generated by an AI assistant for informational purposes only. It does not replace professional clinical evaluation."
  };
};

module.exports = {
  analyzeSymptoms,
};
